### ISSUE TITLE
Uncaught PDOException: SQLSTATE[HY093] (Bounties)

### ISSUE THREAD

**Issue by TheKr1szTEN** [ChristopherDay/Gangster-Legends-V2#86]
There was an error!
File: /var/www/html/modules/installed/bounties/bounties.inc.php
Line: 154
Error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /var/www/html/modules/installed/bounties/bounties.inc.php:154 Stack trace: #0 /var/www/html/modules/installed/bounties/bounties.inc.php(154): PDOStatement->execute() #1 /var/www/html/class/module.php(34): bounties->constructModule() #2 /var/www/html/class/page.php(159): module->__construct() #3 /var/www/html/class/page.php(76): page->load() #4 /var/www/html/init.php(86): page->loadPage() #5 /var/www/html/index.php(5): require('...') #6 {main} thrown
Type: E_RECOVERABLE_ERROR

There was an error!
File: /var/www/html/modules/installed/bounties/bounties.inc.php
Line: 154
Error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /var/www/html/modules/installed/bounties/bounties.inc.php:154 Stack trace: #0 /var/www/html/modules/installed/bounties/bounties.inc.php(154): PDOStatement->execute() #1 /var/www/html/class/module.php(34): bounties->constructModule() #2 /var/www/html/class/page.php(159): module->__construct() #3 /var/www/html/class/page.php(76): page->load() #4 /var/www/html/init.php(86): page->loadPage() #5 /var/www/html/index.php(5): require('...') #6 {main} thrown
Type: E_RECOVERABLE_ERROR

**Comment by TheKr1szTEN** [comment]
Solved

Remove
$active->bindParam(":id", $this->user->id);

(153 line)
